### PR TITLE
Individual app pages and screenshot uploading

### PR DESCRIPTION
**Pull request by celcodioc**
Added #25 and screenshot uploading. The app pages also have breadcrumb support (#24).

App page screenshot:

New config values:
* azure_container_screenshots
* downloadmii_max_screenshots (default 4)

New SQL:
```sql
CREATE TABLE screenshots(
	screenshotId INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	appGuid CHAR(36) NOT NULL,
	imageIndex TINYINT NOT NULL,
	url VARCHAR(255) NOT NULL,
	
	PRIMARY KEY(appGuid, imageIndex);
	
	FOREIGN KEY (appGuid) REFERENCES apps(guid)
);
```

Problems:
* The code is a bit messy
* Not 100% complete (although it should be ready for deployment)
* How will the 3DS app display screenshots? (libpng? conversion to raw rgb when uploading?) This also applies to the app icons we introduced earlier.

### CODE REVIEW

**Comment by filfat** [comment]
The SQL code doesnt work.

Im planning on adding the images to the app at a later date™

Other than that it looks great!! :D

**Comment by celcodioc** [comment]
Yeah, I just noticed and updated the SQL. So, should we merge it? I've tested this a bit and I haven't found any bugs (although I haven't been able to test the actual uploading but the images looks fine when saving locally). So should we merge it now?

**Comment by filfat** [comment]
Yep, you can merge it :D

**Comment by filfat** [comment]
Notice: Undefined variable: fileHandle in D:\home\site\wwwroot\secure\action_publish.php on line 25

**Pull request merged**
